name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # reaguj tylko na tagi wersji typu v1.0.0

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npm run dist

    - name: Create GitHub Release and upload artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload build files to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/multitool Setup ${GITHUB_REF_NAME#refs/tags/}.exe
        asset_name: multitool Setup.exe
        asset_content_type: application/octet-stream
